spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis01?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: com.test.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml